In [30]:
from tensorflow.keras.preprocessing.text import one_hot

In [31]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [32]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [33]:
## Define the vocabulary size
voc_size=10000

In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [35]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr
# these numbers are index postions for 1 and others 0
# for example 2278th index position is having 1 value others 0,similarly 1739 is having 1

[[2278, 1739, 9571, 5304],
 [2278, 1739, 9571, 2228],
 [2278, 6850, 9571, 1700],
 [5282, 2445, 133, 6362, 5434],
 [5282, 2445, 133, 6362, 1643],
 [334, 2278, 8500, 9571, 5585],
 [6291, 3951, 2696, 6362]]

In [36]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequence # --> it was earlier in the this module
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

pad sequence--> some of the sentences have 5 words 56 words 8 words
so we need to make all these sentences of equal size otherwise not be able to train it 
in our RNN, So we will set ip the maximum length
so it will add zeros before or after

In [37]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
# padding='post' will add zeros after

[[   0    0    0    0 2278 1739 9571 5304]
 [   0    0    0    0 2278 1739 9571 2228]
 [   0    0    0    0 2278 6850 9571 1700]
 [   0    0    0 5282 2445  133 6362 5434]
 [   0    0    0 5282 2445  133 6362 1643]
 [   0    0    0  334 2278 8500 9571 5585]
 [   0    0    0    0 6291 3951 2696 6362]]


In [38]:
## feature representation
dim=10

In [39]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [40]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step


array([[[-0.02960631,  0.04801137,  0.0400278 , -0.02089936,
          0.02154669, -0.03477478,  0.01717866, -0.04558021,
         -0.03729407, -0.03304984],
        [-0.02960631,  0.04801137,  0.0400278 , -0.02089936,
          0.02154669, -0.03477478,  0.01717866, -0.04558021,
         -0.03729407, -0.03304984],
        [-0.02960631,  0.04801137,  0.0400278 , -0.02089936,
          0.02154669, -0.03477478,  0.01717866, -0.04558021,
         -0.03729407, -0.03304984],
        [-0.02960631,  0.04801137,  0.0400278 , -0.02089936,
          0.02154669, -0.03477478,  0.01717866, -0.04558021,
         -0.03729407, -0.03304984],
        [ 0.00241334,  0.04774747,  0.03059487, -0.02734684,
         -0.01332542,  0.0179741 ,  0.04831275,  0.01405897,
          0.04369882,  0.00554033],
        [-0.01387401, -0.02530247, -0.02867003, -0.01406846,
          0.03452181,  0.03093341, -0.04095682,  0.02110654,
         -0.03672564, -0.01878853],
        [ 0.02562989, -0.02949967, -0.03645717, -0.0

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0, 2278, 1739, 9571, 5304])

In [43]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [44]:
embedded_docs[0] = embedded_docs[0].reshape(1, embedded_docs[0].shape[0])


In [45]:
import numpy as np
embedded_docs[0] = np.array(embedded_docs[0], dtype='float32')


In [46]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None